# Copyright 2020-2021 The Khronos Group, Inc.
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-mobile:
    name: "Build ${{ matrix.sdk }}"
    strategy:
      matrix:
        include:
          - platform: android
            sdk: android
            architectures: arm64-v8a
    env:
      PARALLEL: -j 2

    runs-on: ubuntu-latest  # Use only Ubuntu for Android build
    steps:
      - uses: actions/checkout@main

      - name: Configure
        shell: bash
        run: |
          cd physx
          ./generate_projects.sh jni-android-arm64-v8a
          cmake ./compiler/jni-android-arm64-v8a-release -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake  -DCMAKE_INSTALL_PREFIX=output -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-24 -DANDROID_LD=lld

      - name: Build for Android ARM64
        shell: bash
        working-directory: ${{github.workspace}}/physx
        run: |
          cmake --build ./compiler/jni-android-arm64-v8a-release/ --config Release --parallel 4
          cmake --build ./compiler/jni-android-arm64-v8a-release/ --config Release --target install

      - uses: actions/upload-artifact@main
        with:
          name: android-arm64
          path: build/output
